spring:
  application:
    name: metrics-accumulator

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    tags:
      application: ${spring.application.name}
maxBatchedMetrics: 200000
sleepTimeBtwMetrics: 200 # milliseconds